// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPSddpdNyvsuqj55qLGzo97GWkpfBuxOs',
    appId: '1:90627798394:web:d71f638a0eb8d8ca3c52c3',
    messagingSenderId: '90627798394',
    projectId: 'hydropure-7bdc3',
    authDomain: 'hydropure-7bdc3.firebaseapp.com',
    storageBucket: 'hydropure-7bdc3.firebasestorage.app',
    measurementId: 'G-RT2X8G58L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnJCg-JYa6Db6neBlcU_j-edynLFWHAbM',
    appId: '1:90627798394:android:917b10629ccfcaf03c52c3',
    messagingSenderId: '90627798394',
    projectId: 'hydropure-7bdc3',
    storageBucket: 'hydropure-7bdc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZE6PwDYtGXftV9zcl3zoD38JPac5nrzI',
    appId: '1:90627798394:ios:9dd48877a85e85703c52c3',
    messagingSenderId: '90627798394',
    projectId: 'hydropure-7bdc3',
    storageBucket: 'hydropure-7bdc3.firebasestorage.app',
    iosClientId: '90627798394-mpaoj2g16t4ff7pbt1u8ru02p0l07fs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydropure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZE6PwDYtGXftV9zcl3zoD38JPac5nrzI',
    appId: '1:90627798394:ios:9dd48877a85e85703c52c3',
    messagingSenderId: '90627798394',
    projectId: 'hydropure-7bdc3',
    storageBucket: 'hydropure-7bdc3.firebasestorage.app',
    iosClientId: '90627798394-mpaoj2g16t4ff7pbt1u8ru02p0l07fs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydropure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPSddpdNyvsuqj55qLGzo97GWkpfBuxOs',
    appId: '1:90627798394:web:2f85094c3639e3203c52c3',
    messagingSenderId: '90627798394',
    projectId: 'hydropure-7bdc3',
    authDomain: 'hydropure-7bdc3.firebaseapp.com',
    storageBucket: 'hydropure-7bdc3.firebasestorage.app',
    measurementId: 'G-WNFJJ5MJKB',
  );
}
